version : 1
formatters:
  myformatter: 
    format: '%(asctime)s | %(message)s | %(levelname)s | %(funcName)s'

handlers:
  console:
    class: logging.StreamHandler
    level : DEBUG
    formatter : myformatter
    stream : ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    level : DEBUG
    formatter : myformatter
    filename : file.log

root:
    level : CRITICAL
    handlers : [console, file_handler]

